import type { Metadata } from "next";
import {
  Public_Sans,
  Castoro,
  Lora,
  Roboto,
  Frank_Ruhl_Libre,
} from "next/font/google";
import "./globals.css";

const publicSans = Public_Sans({
  subsets: ["latin"],
  variable: "--font-publicsans",
});

const frank_ruhl_libre = Frank_Ruhl_Libre({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-franklibre",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto",
});

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
});

const castoro = Castoro({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-castoro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${frank_ruhl_libre.variable} ${roboto.variable} ${publicSans.variable} ${castoro.variable} ${lora.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
